name: Tinybird CI

on:
  pull_request:
    paths:
      - "src/lib/tinybird.ts"
      - "tinybird.config.*"
      - "tinybird/**"

env:
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  tinybird:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Create preview branch
        run: pnpm run tinybird:preview
